### ISSUE TITLE
蝦皮每日簽到

### ISSUE THREAD

**Issue by Yswag** [Black-Magic-Lab/Surge#3]
你好，從前幾天開始每日簽到都返回403，似乎是請求時沒有用蝦皮的User Agent的原因，加上後可以正常簽到了
![image](https://github.com/Black-Magic-Lab/Surge/assets/91155348/d4ec9cf9-9a96-42c1-8199-6484bad6b5e7)

**Comment by hirakujira** [comment]
OK 已經更新腳本
